---
apiVersion: v1
kind: Secret
metadata:
  name: gitguardian-nhi-scout-secrets
stringData:
  AZURE_CLIENT_ID: "6e85cc76-ae23-49ae-bd3a-7a3760916044"
  AZURE_CLIENT_SECRET: "my_client_secret"
  AZURE_SUBSCRIPTION_ID: "6870dab5-c77a-418d-97c8-4ee3c4d1db45"
  AZURE_TENANT_ID: "6e85cc76-ae23-49ae-bd3a-7a3760916044"
