---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      azurekeyvault:
        type: azurekeyvault
        subscription_id: "${AZURE_SUBSCRIPTION_ID}"
        fetch_all_versions: true

