---
apiVersion: v1
kind: Secret
metadata:
  name: ggscout-secrets
stringData:
  GITGUARDIAN_API_KEY: "your_gitguardian_token"

  # CyberArk Self-Hosted API credentials
  CYBERARK_LOGIN: "host/your-workload-login"
  CYBERARK_API_KEY: "your_cyberark_api_key"
  CYBERARK_SERVER_URL: "https://your-cyberark-server.example.com"
  CYBERARK_ACCOUNT: "your_cyberark_account"
