---
repos:
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3    # or other specific tag
  hooks:
  - id: yamlfmt
    files: .*.(yaml|yml)
    exclude: (templates|.github)/
    args: [--mapping, '2', --sequence, '2', --offset, '0', --preserve-quotes, --preserve_null]
- repo: local
  hooks:
  - entry: mise run bundle-schemas
    id: schema-bundle
    language: system
    name: schema-bundle
    pass_filenames: false
  - entry: mise run test
    id: helm-unittest
    language: system
    name: helm-unittest
    pass_filenames: false
  - entry: mise run lint
    id: helm-lint
    language: system
    name: helm-lint
    pass_filenames: false
  - entry: mise run generate-docs
    id: generate-docs
    language: system
    name: generate-docs
    pass_filenames: false
