{{- if and .Values.serviceAccount.create .Values.clusterRole.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nhi-scout.fullname" . }}
  labels:
    {{- include "nhi-scout.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nhi-scout.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "nhi-scout.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
