---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nhi-scout.fullname" . }}
  labels:
    {{- include "nhi-scout.labels" . | nindent 4 }}
type: Opaque
data:
  config.yml: {{ toYaml .Values.inventory.config | b64enc | quote}}
