---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nhi-scout.fullname" . }}
  labels:
    {{- include "nhi-scout.labels" . | nindent 4 }}
type: Opaque
data:
  config.yml: {{ toYaml .Values.inventory.config | b64enc | quote}}

{{- if .Values.caBundle.certs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ca-bundle" (include "nhi-scout.fullname" .) }}
  labels:
    {{- include "nhi-scout.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.caBundle.certs | b64enc }}
{{- end }}
