---
apiVersion: v1
kind: Secret
metadata:
  name: ggscout-secrets
stringData:
  # CyberArk Workload authentication
  CYBERARK_WORKLOAD_LOGIN: "your-workload-login"
  CYBERARK_WORKLOAD_API_KEY: "your-workload-api-key"

  # CyberArk subdomain
  CYBERARK_SUBDOMAIN: "your-cyberark-subdomain"

  # GitGuardian API token
  GITGUARDIAN_API_KEY: "your_gitguardian_token"
