---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      kubernetes:
        type: k8s
        config_source: incluster # incluster means that the Scout is scanning the k8s cluster is running on
        name: my-cluster # cluster name must be provided when `incluster` is used
        namespaces: # List of namespaces or null
        - default
        - kube-system
    # To upload, set the gitguardian URL and tokens. Ensure the endpoint path ends with /v1
    # This is optional: omit this to prevent uploading and to only test collection.
    gitguardian:
      endpoint: "https://my-gg-instance/v1"
      api_token: "${GITGUARDIAN_API_KEY}"
  jobs:
    # Job to fetch defined sources
    fetch:
      # Set to `false` to disable the job
      enabled: true
      # Run every 15 minutes
      schedule: '*/15 * * * *'
      send: true

envFrom:
- secretRef:
    name: ggscout-secrets
