---
apiVersion: v1
kind: Secret
metadata:
  name: gitguardian-nhi-scout-secrets
stringData:
  GG_API_TOKEN: "your_gitguardian_token"

  CONJUR_WORKLOAD_ID: "your_workload_id"
  CONJUR_WORKLOAD_API_KEY: "workload_api_key"
