---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      conjur_cloud:
        type: conjurcloud
        fetch_all_versions: true
        subdomain: "conjursubdomain"
        auth_mode: "workload"
        login: "${CONJUR_WORKLOAD_ID}"
        api_key: "${CONJUR_WORKLOAD_API_KEY}"

    gitguardian:
      endpoint: "https://my-gg-instance/v1"
      api_token: "${GG_API_TOKEN}"
  jobs:
    # Job to fetch defined sources
    fetch:
      # Set to `false` to disable the job
      enabled: true
      # Run every 15 minutes
      schedule: '*/15 * * * *'
      send: true
    # Job to be able to sync/write secrets from GitGuardian into you vault
    sync:
      # Set to `false` to disable the job
      enabled: true
      # Run every minute
      schedule: '* * * * *'

envFrom:
- secretRef:
    name: gitguardian-nhi-scout-secrets
