---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      gitlab:
        type: gitlabci
        token: "${GITLAB_ACCESS_TOKEN}" # Replace with the GitLab CI token
        url: "https://your-gitlab-address-here" # GitLab URL
    # To upload, set the gitguardian URL and tokens. Ensure the endpoint path ends with /v1
    # This is optional: omit this to prevent uploading and to only test collection.
    gitguardian:
      endpoint: "https://my-gg-instance/v1"
      api_token: "${GITGUARDIAN_API_KEY}"
  jobs:
    # Job to fetch defined sources
    fetch:
      # Set to `false` to disable the job
      enabled: true
      # Run every 15 minutes
      schedule: '*/15 * * * *'
      send: true

envFrom:
- secretRef:
    name: ggscout-secrets
