---
apiVersion: v1
kind: Secret
metadata:
  name: ggscout-secrets
stringData:
  GITGUARDIAN_API_KEY: "your_gitguardian_token"

  # CyberArk Self-Hosted credentials
  CYBERARK_USERNAME: "your_cyberark_username"
  CYBERARK_PASSWORD: "your_cyberark_password"
  CYBERARK_SERVER_URL: "https://your-cyberark-server.example.com"
  CYBERARK_ACCOUNT: "your_cyberark_account"
