{{- if and .Values.inventory.config.gitguardian .Values.inventory.jobs .Values.inventory.jobs.ping }}
{{ include "ggscout.cronjob" (merge (dict "cronjob_name" "ping" "command" "ping" "schedule" .Values.inventory.jobs.ping.schedule "backOffLimit" .Values.inventory.jobs.ping.backOffLimit "ttlSecondsAfterFinished" .Values.inventory.jobs.ping.ttlSecondsAfterFinished) .) -}}
{{- end }}
