{{- if and .Values.inventory.config.gitguardian .Values.inventory.jobs.sync.enabled }}
{{ include "ggscout.cronjob" (merge (dict "cronjob_name" "sync" "command" "sync-secrets" "schedule" .Values.inventory.jobs.sync.schedule "backOffLimit" .Values.inventory.jobs.sync.backOffLimit "ttlSecondsAfterFinished" .Values.inventory.jobs.sync.ttlSecondsAfterFinished) .) -}}
{{- end }}
