{{- if and .Values.inventory.config.gitguardian .Values.inventory.jobs .Values.inventory.jobs.fetch .Values.inventory.jobs.fetch.enabled }}

{{ $command := "fetch" -}}

{{- if .Values.inventory.jobs.fetch.send }}
{{ $command = "fetch-and-send" -}}
{{- end }}

{{ include "ggscout.cronjob" (merge (dict "cronjob_name" "inventory" "command" $command "schedule" .Values.inventory.jobs.fetch.schedule "backOffLimit" .Values.inventory.jobs.fetch.backOffLimit "ttlSecondsAfterFinished" .Values.inventory.jobs.fetch.ttlSecondsAfterFinished ) .) -}}
{{- end }}
