---
apiVersion: v1
kind: Secret
metadata:
  name: gitguardian-nhi-scout-secrets
stringData:
  # OUTPUT_PATH is the path that the Scout `fetch` command is using to write the inventory
  OUTPUT_PATH: "/tmp/output/inventory.json"
