---
apiVersion: v1
kind: Secret
metadata:
  name: ggscout-secrets
stringData:
  GITGUARDIAN_API_KEY: "your_gitguardian_token"

  # This can be found by clicking on "Token API documentation" in the Settings > REST API section of the Secret Server UI
  DELINEA_TLD: "your_delinea_tld"
  DELINEA_CLIENT_ID: "your_delinea_client_id"
  DELINEA_CLIENT_SECRET: "your_delinea_client_secret"
  DELINEA_TENANT: "your_delinea_tenant"
