---
# yaml-language-server: $schema=../../values.schema.json

# Custom certificates are configured by setting the caBundle parameter.

caBundle:
  # Specify CA certificates to inject (PEM format)
  certs: |
    -----BEGIN CERTIFICATE-----
    Cert 1
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    Cert 2
    -----END CERTIFICATE-----
  # Or you can specify a secret containing CA certificates to inject
  existingSecret: my-custom-certificates
  # Specify secret key under the CA certificate is stored
  existingSecretKey: ca.crt

inventory:
  config:
    sources:
      gitlab:
        type: gitlabci
        token: gitlab-token # Replace with the GitLab CI token
        url: https://gitlab.com # GitLab URL
    gitguardian:
      endpoint: "https://my-gg-instance/v1"
      api_token: "my_api_token"
